version: 2
jobs:
  build:
    docker:
      - image: 303634175659.dkr.ecr.us-east-2.amazonaws.com/circleci:play-app
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # ... steps for building/testing app ...

      - setup_remote_docker:   # (2)
          docker_layer_caching: false # (3)

      - run:
          command: |
            cd OfflineReverseGeocode
            mvn install

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.sbt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # build and push Docker image
      - run: |
          sbt docker:publish

      - save_cache:
          paths:
            - ~/.m2
            - ~/.ivy2
            - ~/.sbt
          key: v1-dependencies-{{ checksum "build.sbt" }}

